CARGANDO DATOS CON NUMPY

In [4]:
import csv
import numpy
filename = 'data/pima-indians-diabetes.csv'
raw_data = open(filename, 'r')
reader = csv.reader(raw_data, delimiter=',', quoting = csv.QUOTE_NONE)
x = list(reader)
data = numpy.array(x).astype('float')
print(data)

[[  6. 148.  72. ... 627.  50.   1.]
 [  1.  85.  66. ... 351.  31.   0.]
 [  8. 183.  64. ... 672.  32.   1.]
 ...
 [  5. 121.  72. ... 245.  30.   0.]
 [  1. 126.  60. ... 349.  47.   1.]
 [  1.  93.  70. ... 315.  23.   0.]]


In [3]:
import csv
import numpy as np

filename = 'data/abalone.csv'
with open(filename, 'r') as raw_data:
    reader = csv.reader(raw_data, delimiter=',', quoting=csv.QUOTE_NONE)
    x = list(reader)

# Eliminar la primera columna (columna de sexo)
for row in x:
    del row[0]

data = np.array(x).astype('float')
print(data.shape)
print(data)


(4177, 8)
[[ 0.455   0.365   0.095  ...  0.101   0.15   15.    ]
 [ 0.35    0.265   0.09   ...  0.0485  0.07    7.    ]
 [ 0.53    0.42    0.135  ...  0.1415  0.21    9.    ]
 ...
 [ 0.6     0.475   0.205  ...  0.2875  0.308   9.    ]
 [ 0.625   0.485   0.15   ...  0.261   0.296  10.    ]
 [ 0.71    0.555   0.195  ...  0.3765  0.495  12.    ]]


In [11]:
import csv
import numpy as np

filename = 'data/breast-cancer.csv'

with open(filename, 'r') as raw_data:
    reader = csv.reader(raw_data, delimiter=',', quoting=csv.QUOTE_NONE)
    x = list(reader)

# Convertimos a array de objetos por si hay texto
data = np.array(x)

# Mostrar forma: (filas, columnas)
print(data.shape)





(286, 10)


In [26]:
import csv
import numpy as np

filename = 'data/countries.csv'

# Abrir y leer el archivo CSV
with open(filename, 'r', encoding='utf-8') as raw_data:
    reader = csv.reader(raw_data, delimiter=';', quoting=csv.QUOTE_MINIMAL)
    data = list(reader)

# Extraer encabezado
header = data[0]
rows = data[1:]

# Convertir a arreglo de NumPy (como texto inicialmente)
data_np = np.array(rows)

# Identificar columnas numéricas y de texto
numeric_data = []
text_data = []

# Recorremos cada columna para separarlas según si es numérica o no
for col_index in range(data_np.shape[1]):
    try:
        # Intentamos convertir toda la columna a float
        col = data_np[:, col_index].astype(float)
        numeric_data.append(col)
    except ValueError:
        # Si falla, la tratamos como texto
        col = data_np[:, col_index]
        text_data.append(col)

# Convertimos a arrays
numeric_array = np.array(numeric_data).T  # Transpuesta para que cada fila sea un país
text_array = np.array(text_data).T

# Mostrar formas
print("Columnas numéricas:", numeric_array.shape)
print("Columnas de texto:", text_array.shape)




Columnas numéricas: (252, 4)
Columnas de texto: (252, 15)


In [27]:
import csv
import numpy as np

filename = 'data/credit-g.csv'

# Leer archivo, eliminando comillas simples
with open(filename, 'r', encoding='utf-8') as file:
    reader = csv.reader(file)
    data = [ [cell.strip().replace("'", "") for cell in row] for row in reader ]

# Separar encabezado y datos
header = data[0]
rows = data[1:]

# Convertir a arreglo numpy como texto inicialmente
data_np = np.array(rows)

# Separar columnas numéricas y de texto
numeric_data = []
text_data = []
numeric_headers = []
text_headers = []

for col_index in range(data_np.shape[1]):
    try:
        col = data_np[:, col_index].astype(float)
        numeric_data.append(col)
        numeric_headers.append(header[col_index])
    except ValueError:
        text_data.append(data_np[:, col_index])
        text_headers.append(header[col_index])

# Convertir a arrays finales
numeric_array = np.array(numeric_data).T
text_array = np.array(text_data).T

# Imprimir resumen
print("Columnas numéricas:", numeric_headers)
print("Forma de numeric_array:", numeric_array.shape)
print("Columnas de texto:", text_headers)
print("Forma de text_array:", text_array.shape)


Columnas numéricas: ['duration', 'credit_amount', 'installment_commitment', 'residence_since', 'age', 'existing_credits', 'num_dependents']
Forma de numeric_array: (1000, 7)
Columnas de texto: ['checking_status', 'credit_history', 'purpose', 'savings_status', 'employment', 'personal_status', 'other_parties', 'property_magnitude', 'other_payment_plans', 'housing', 'job', 'own_telephone', 'foreign_worker', 'class']
Forma de text_array: (1000, 14)


In [33]:
import csv
import numpy as np

filename = 'data/glass.csv'

# Leer el archivo CSV
with open(filename, 'r', encoding='utf-8') as raw_data:
    reader = csv.reader(raw_data, delimiter=',')
    x = list(reader)

header = x[0]      # Encabezados
rows = x[1:]       # Datos

# Limpiar comillas y espacios
cleaned_rows = []
for row in rows:
    cleaned_row = [item.strip().replace("'", "") for item in row]
    cleaned_rows.append(cleaned_row)

# Identificar columnas numéricas
numeric_indices = []
for i in range(len(cleaned_rows[0])):
    try:
        float(cleaned_rows[0][i])
        numeric_indices.append(i)
    except ValueError:
        continue  # Saltar si no se puede convertir

# Filtrar solo columnas numéricas
numeric_data = []
for row in cleaned_rows:
    numeric_row = [row[i] for i in numeric_indices]
    numeric_data.append(numeric_row)

# Convertir a numpy array
data = np.array(numeric_data).astype(float)

# Mostrar forma
print(data.shape)



(214, 9)


In [39]:
import csv
import numpy as np

# Leer datos ignorando la cabecera si la tiene
data = np.genfromtxt('data/housing.csv', delimiter=None)

print(data.shape)



(506, 14)


In [41]:
import csv
import numpy as np

filename = 'data/iris.data.csv'

# Leer el archivo ignorando líneas vacías
with open(filename, 'r') as f:
    reader = csv.reader(f)
    rows = [row for row in reader if row]  # eliminar filas vacías

# Separar características (float) y etiquetas (string)
X = []
y = []

for row in rows:
    # Último valor es la clase, los anteriores son floats
    X.append([float(value) for value in row[:-1]])
    y.append(row[-1])

# Convertir a arrays numpy
X = np.array(X)
y = np.array(y)

# Mostrar forma de los datos
print("Shape de X (datos):", X.shape)
print("Shape de y (etiquetas):", y.shape)


Shape de X (datos): (150, 4)
Shape de y (etiquetas): (150,)


In [42]:
import csv
import numpy
filename = 'data/pima-indians-diabetes.data.csv'
raw_data = open(filename, 'r')
reader = csv.reader(raw_data, delimiter=',', quoting = csv.QUOTE_NONE)
x = list(reader)
data = numpy.array(x).astype('float')
print(data.shape)

(768, 9)


In [44]:
import csv
import numpy as np

filename = 'data/sonar.all-data.csv'

# Leer el archivo correctamente
with open(filename, 'r') as raw_data:
    reader = csv.reader(raw_data)
    rows = list(reader)

# Separar datos numéricos y etiquetas
X = [row[:-1] for row in rows]  # 60 columnas numéricas
y = [row[-1] for row in rows]  # 1 columna de clase ('R' o 'M')

# Convertir datos numéricos a float
X = np.array(X).astype(float)
y = np.array(y)  # Si quieres codificarla a 0/1, dime y te ayudo

# Ver formas
print("Shape de X:", X.shape)
print("Shape de y:", y.shape)


Shape de X: (208, 60)
Shape de y: (208,)


In [46]:
import csv
import numpy

filename = 'data/soybean.csv'
raw_data = open(filename, 'r')
reader = csv.reader(raw_data, delimiter=',', quoting=csv.QUOTE_NONE)
x = list(reader)

# Convertir a numpy array sin intentar pasarlo a float (por si hay texto)
data = numpy.array(x)

print(data.shape)


(684, 36)


In [47]:
import csv
import numpy

filename = 'data/wisconsin.csv'
raw_data = open(filename, 'r')
reader = csv.reader(raw_data, delimiter=',', quoting=csv.QUOTE_NONE)
x = list(reader)

# Convertir a numpy array sin intentar pasarlo a float (por si hay texto)
data = numpy.array(x)

print(data.shape)


(700, 11)
